# action.yml
name: 'Stark Accessibility Checker'
description: "Run your server on GitHub's infra and scan for accessibility issues with Stark's tooling"
branding:
  icon: 'code'
  color: 'purple'
inputs:
  setup: # set up the container
    description: 'Set up the current container. Here you can install dependencies related to the container. E.g. install a node version. Use the node version.'
    required: false
    default: 'echo "Nothing to setup"'
  prebuild: # install project dependencies
    description: 'Install project dependencies. E.g. npm install'
    required: false
    default: 'echo "Nothing to prebuild"'
  build: # build the project
    description: 'Build the project. E.g npm build'
    required: false
    default: 'echo "Nothing to build"'
  serve: # serve the project on localhost
    description: 'Serve the project. E.g npm start'
    required: false
    default: 'echo "Nothing to serve"'
  cleanup:
    description: 'Run a cleanup if needed.'
    required: false
    default: 'echo "Nothing to cleanup"'
  urls:
    description: 'A list of URLs to be scanned, with each URL belonging to its own line. This value follows YAML conventions for multiline strings.'
    required: true
    default: 'https://getstark.co'
  wait_time:
    description: 'Time in milliseconds to wait before running the scanner. A rough time delay for your server to start'
    required: false
    default: 5000
  min_score:
    description: 'Minimum score for the action to pass. A number from 0 to 100'
    required: false
    default: 0
  token:
    description: "Stark token required to send data back to stark web. The cli doesn't post data if token is not provided"
    required: false
  skip_errors:
    description: 'Continue to scanning the next url if an error occurs while scanning a url'
    required: false
    default: false
  scan_delay:
    description: 'Delay running a scan after navigation has completed (wait for something to happen on the page)'
    required: false
    default: 100
  viewport:
    description: 'Browser viewport [width]x[height]'
    required: false
    default: '800x600'
  requires_basic_auth:
    description: 'Set to true if your URL uses basic HTTP authentication When true, you must also provide values for "username" and "password".'
    required: false
    default: false
  requires_page_auth:
    description: 'Set to `true` if your URL requires authentication. When true, you must also provide values for "username", "password", "login-page-url", "username-selector", "password-selector", and "submit-button-selector".'
    required: false
    default: false
  username:
    description: 'Username for basic or page authentication'
    required: false
  password:
    description: 'Password for basic or page authentication'
    required: false
  login_page_url:
    description: 'URL for your login page (usually different than the URL you want to scan). Used with page authentication.'
    required: false
  username_selector:
    description: 'Selector (https://playwright.dev/docs/locators#locate-by-css-or-xpath) for the username input on the login page. Used with page authentication.'
    required: false
  password_selector:
    description: 'Selector (https://playwright.dev/docs/locators#locate-by-css-or-xpath) for the password input on the login page. Used with page authentication.'
    required: false
  submit_button_selector:
    description: 'Selector (https://playwright.dev/docs/locators#locate-by-css-or-xpath) for the submit button on the login page. Used with page authentication.'
    required: false
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.setup }}
    - ${{ inputs.prebuild }}
    - ${{ inputs.build }}
    - ${{ inputs.serve }}
    - ${{ inputs.cleanup }}
    - ${{ inputs.urls }}
    - ${{ inputs.min_score }}
    - ${{ inputs.wait_time }}
    - ${{ inputs.token }}
    - ${{ inputs.viewport }}
    - ${{ inputs.skip_errors }}
    - ${{ inputs.scan_delay }}
    - ${{ inputs.requires_basic_auth }}
    - ${{ inputs.requires_page_auth }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.login_page_url }}
    - ${{ inputs.username_selector }}
    - ${{ inputs.password_selector }}
    - ${{ inputs.submit_button_selector }}
